package com.city.sprinbboot.database2code.com.xjs.common.listener;

import com.city.sprinbboot.database2code.com.xjs.common.util.RedisUtil;
import redis.clients.jedis.Jedis;

public class ExportNodesContextListener {

    /**
     * 加载导入导出用到的字段
     * PT 普通字段项,格式PT-字段英文-字段中文
     * DICT 数据字典字段项,格式DICT-字段英文|字典ID-缓存key|字段中文
     * RADIO 单选字段项,格式RADIO-字段英文-字段中文
     * STATE 状态字段项,格式STATE-字段英文-字段中文
     */
    public void addRedis() {
        Jedis jedis = RedisUtil.getJedis();
        jedis.del("hjrk");
        jedis.rpush("hjrk", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("hjrk", "PT-NAME-姓名");
        jedis.rpush("hjrk", "PT-USEDNAME-曾用名");
        jedis.rpush("hjrk", "PT-ORG_NAME-所属网格");
        jedis.rpush("hjrk", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("hjrk", "PT-BIRTHDATE-出生日期");
        jedis.rpush("hjrk", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("hjrk", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("hjrk", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("hjrk", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("hjrk", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("hjrk", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("hjrk", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("hjrk", "PT-OCCUPATION-职业");
        jedis.rpush("hjrk", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("hjrk", "PT-CONTACT-联系方式");
        jedis.rpush("hjrk", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("hjrk", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("hjrk", "PT-PRESENTPLACE-现住地");
        jedis.rpush("hjrk", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("hjrk", "DICT-UNIFORMIDENTITY|UNIFORMIDENTITYID-rkyz|人户一致标识");
        jedis.rpush("hjrk", "PT-HOUSEHOLDNO-户号");
        jedis.rpush("hjrk", "PT-HOUSEHOLDCITIZENIDNO-户主公民身份证号");
        jedis.rpush("hjrk", "PT-HOUSEHOLDNAME-户主公民姓名");
        jedis.rpush("hjrk", "DICT-RELATIONSHIPWITHHOUSEHOLD|RELATIONSHIPWITHHOUSEHOLDID-yhzgx|与户主关系");
        jedis.rpush("hjrk", "PT-HOUSEHOLDCONTACT-户主联系方式");

        jedis.del("ldrk");
        jedis.rpush("ldrk", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("ldrk", "PT-NAME-姓名");
        jedis.rpush("ldrk", "PT-USEDNAME-曾用名");
        jedis.rpush("ldrk", "PT-ORG_NAME-所属网格");
        jedis.rpush("ldrk", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("ldrk", "PT-BIRTHDATE-出生日期");
        jedis.rpush("ldrk", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("ldrk", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("ldrk", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("ldrk", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("ldrk", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("ldrk", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("ldrk", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("ldrk", "PT-OCCUPATION-职业");
        jedis.rpush("ldrk", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("ldrk", "PT-CONTACT-联系方式");
        jedis.rpush("ldrk", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("ldrk", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("ldrk", "PT-PRESENTPLACE-现住地");
        jedis.rpush("ldrk", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("ldrk", "DICT-INFLOWREASON|INFLOWREASONID-lryy|流入原因");
        jedis.rpush("ldrk", "DICT-CERTIFICATETYPE|CERTIFICATETYPEID-bzlx|办证类型");
        jedis.rpush("ldrk", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("ldrk", "PT-REGISTRATIONDATE-登记日期");
        jedis.rpush("ldrk", "PT-CERTIFICATEEXPIRATIONDATE-证件到期日期");
        jedis.rpush("ldrk", "DICT-RESIDENCETYPE|RESIDENCETYPEID-zslx|住所类型");
        jedis.rpush("ldrk", "RADIO-ISKEYPERSON-是否重点关注人员");

        jedis.del("lsry");
        jedis.rpush("lsry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("lsry", "PT-NAME-姓名");
        jedis.rpush("lsry", "PT-USEDNAME-曾用名");
        jedis.rpush("lsry", "PT-ORG_NAME-所属网格");
        jedis.rpush("lsry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("lsry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("lsry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("lsry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("lsry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("lsry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("lsry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("lsry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("lsry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("lsry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("lsry", "PT-OCCUPATION-职业");
        jedis.rpush("lsry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("lsry", "PT-CONTACT-联系方式");
        jedis.rpush("lsry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("lsry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("lsry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("lsry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("lsry", "DICT-HEALTH|HEALTHID-jkzk|健康状况");
        jedis.rpush("lsry", "PT-PERSONALANNUALINCOME-个人年收入");
        jedis.rpush("lsry", "DICT-UNIFORMIDENTITY|UNIFORMIDENTITYID-rhyz|人户一致标识");
        jedis.rpush("lsry", "DICT-REARPERSONTYPE|REARPERSONTYPEID-lsrylx|留守人员类型");
        jedis.rpush("lsry", "PT-FAMILYPRINCIPALIDNO-家庭成员身份证号码");
        jedis.rpush("lsry", "PT-FAMILYPRINCIPALNAME-家庭成员姓名");
        jedis.rpush("lsry", "DICT-FAMILYPRINCIPALHEALTH|FAMILYPRINCIPALHEALTHID-jkzk|家庭成员健康状况");
        jedis.rpush("lsry", "DICT-RELATIONSHIPWITHREARPERSON|RELATIONSHIPWITHREARPERSONID-yhzgx|与留守人员关系");
        jedis.rpush("lsry", "PT-FAMILYPRINCIPALCONTACT-家庭成员联系方式");
        jedis.rpush("lsry", "PT-FAMILYPRINCIPALJOBPLACEDETAILS-家庭成员工作详细地址");
        jedis.rpush("lsry", "PT-HOUSEHOLDANNUALINCOME-家庭年收入");
        jedis.rpush("lsry", "PT-DIFFICULTIESANDAPPEALS-困难及诉求");
        jedis.rpush("lsry", "PT-HELPINGSITUATION-帮扶情况");

        jedis.del("xmsfry");
        jedis.rpush("xmsfry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("xmsfry", "PT-NAME-姓名");
        jedis.rpush("xmsfry", "PT-USEDNAME-曾用名");
        jedis.rpush("xmsfry", "PT-ORG_NAME-所属网格");
        jedis.rpush("xmsfry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("xmsfry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("xmsfry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("xmsfry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("xmsfry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("xmsfry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("xmsfry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("xmsfry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("xmsfry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("xmsfry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("xmsfry", "PT-OCCUPATION-职业");
        jedis.rpush("xmsfry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("xmsfry", "PT-CONTACT-联系方式");
        jedis.rpush("xmsfry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("xmsfry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("xmsfry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("xmsfry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("xmsfry", "RADIO-ISRECIDIVIST-是否累犯");
        jedis.rpush("xmsfry", "DICT-OLDCHARGE|OLDCHARGEID-zm|原罪名");
        jedis.rpush("xmsfry", "PT-ORIGINALSENTENCE-原判刑期");
        jedis.rpush("xmsfry", "PT-IMPRISONMENTPLACE-服刑场所");
        jedis.rpush("xmsfry", "PT-RELEASEDATE-释放日期");
        jedis.rpush("xmsfry", "DICT-RISKASSESSMENTTYPE|RISKASSESSMENTTYPEID-wxxpg|危险性评估类型");
        jedis.rpush("xmsfry", "PT-CONNECTIONDATE-衔接日期");
        jedis.rpush("xmsfry", "DICT-CONNECTIONSITUATION|CONNECTIONSITUATIONID-xjqk|衔接情况");
        jedis.rpush("xmsfry", "PT-PLACEMENTDATE-安置日期");
        jedis.rpush("xmsfry", "DICT-PLACEMENTSITUATION|PLACEMENTSITUATIONID-azqk|安置情况");
        jedis.rpush("xmsfry", "PT-NOPLACEMENTREASON-未安置原因");
        jedis.rpush("xmsfry", "PT-HELPINGSITUATION-帮教情况");
        jedis.rpush("xmsfry", "RADIO-ISRECIDIVISM-是否重新犯罪");
        jedis.rpush("xmsfry", "PT-RECIDIVISMCHARGE-重新犯罪罪名");

        jedis.del("sqjzry");
        jedis.rpush("sqjzry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("sqjzry", "PT-NAME-姓名");
        jedis.rpush("sqjzry", "PT-USEDNAME-曾用名");
        jedis.rpush("sqjzry", "PT-ORG_NAME-所属网格");
        jedis.rpush("sqjzry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("sqjzry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("sqjzry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("sqjzry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("sqjzry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("sqjzry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("sqjzry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("sqjzry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("sqjzry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("sqjzry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("sqjzry", "PT-OCCUPATION-职业");
        jedis.rpush("sqjzry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("sqjzry", "PT-CONTACT-联系方式");
        jedis.rpush("sqjzry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("sqjzry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("sqjzry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("sqjzry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("sqjzry", "PT-CORRECTPERSONNO-社区矫正人员编号");
        jedis.rpush("sqjzry", "PT-OLDDETENTIONPLACE-原羁押场所");
        jedis.rpush("sqjzry", "DICT-CORRECTTYPE|CORRECTTYPEID-jzlb|矫正类别");
        jedis.rpush("sqjzry", "DICT-CASETYPE|CASETYPEID-ajlb|案件类别");
        jedis.rpush("sqjzry", "PT-SPECIFICCHARGE-具体罪名");
        jedis.rpush("sqjzry", "PT-ORIGINALSENTENCE-原判刑期");
        jedis.rpush("sqjzry", "PT-ORIGINALSENTENCEDATEFROM-原判刑开始日期");
        jedis.rpush("sqjzry", "PT-ORIGINALSENTENCEDATEEND-原判刑结束日期");
        jedis.rpush("sqjzry", "PT-CORRECTDATEFROM-矫正开始日期");
        jedis.rpush("sqjzry", "PT-CORRECTDATEEND-矫正结束日期");
        jedis.rpush("sqjzry", "DICT-ACCEPTANCEMODE|ACCEPTANCEMODEID-jsfs|接受方式");
        jedis.rpush("sqjzry", "DICT-FOURCASES|FOURCASESID-ssqk|四史情况");
        jedis.rpush("sqjzry", "RADIO-ISRECIDIVIST-是否累惯犯");
        jedis.rpush("sqjzry", "DICT-THREECIRCUMSTANCES|THREECIRCUMSTANCESID-ssqk1|三涉情况");
        jedis.rpush("sqjzry", "RADIO-ISCORRECTIVETEAM-是否建立矫正小组");
        jedis.rpush("sqjzry", "DICT-CORRECTIVETEAMPERSON|CORRECTIVETEAMPERSONID-jzxzryzclx|矫正小组组成情况");
        jedis.rpush("sqjzry", "DICT-CORRECTRELEASETYPE|CORRECTRELEASETYPEID-jzjczzlx|矫正解除终止类型");
        jedis.rpush("sqjzry", "RADIO-ISUNMANAGED-是否有脱管");
        jedis.rpush("sqjzry", "PT-UNMANAGEDREASON-脱管原因");
        jedis.rpush("sqjzry", "PT-CHECKUNMANAGED-检查监督脱管情况");
        jedis.rpush("sqjzry", "PT-UNMANAGEDCORRECTSITUATION-脱管纠正情况");
        jedis.rpush("sqjzry", "RADIO-ISLEAKYMANAGED-是否有漏管");
        jedis.rpush("sqjzry", "PT-LEAKYMANAGEDREASON-漏管原因");
        jedis.rpush("sqjzry", "PT-CHECKLEAKYMANAGED-检查监督漏管情况");
        jedis.rpush("sqjzry", "PT-LEAKYMANAGEDCORRECTSITUATION-漏管纠正情况");
        jedis.rpush("sqjzry", "PT-REWARDPUNISHSITUATION-奖惩情况");
        jedis.rpush("sqjzry", "PT-PUNISHCHANGEIMPLEMENTSITUATION-刑罚变更执行情况");
        jedis.rpush("sqjzry", "RADIO-ISRECIDIVISM-是否重新犯罪");
        jedis.rpush("sqjzry", "PT-RECIDIVISMCHARGE-重新犯罪罪名");

        jedis.del("jszahz");
        jedis.rpush("jszahz", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("jszahz", "PT-NAME-姓名");
        jedis.rpush("jszahz", "PT-USEDNAME-曾用名");
        jedis.rpush("jszahz", "PT-ORG_NAME-所属网格");
        jedis.rpush("jszahz", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("jszahz", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("jszahz", "PT-BIRTHDATE-出生日期");
        jedis.rpush("jszahz", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("jszahz", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("jszahz", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("jszahz", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("jszahz", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("jszahz", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("jszahz", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("jszahz", "PT-OCCUPATION-职业");
        jedis.rpush("jszahz", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("jszahz", "PT-CONTACT-联系方式");
        jedis.rpush("jszahz", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("jszahz", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("jszahz", "PT-PRESENTPLACE-现住地");
        jedis.rpush("jszahz", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("jszahz", "DICT-FAMILYECONOMICSITUATION|FAMILYECONOMICSITUATIONID-jtjjzk|家庭经济状况");
        jedis.rpush("jszahz", "RADIO-ISALLOWANCES-是否纳入低保");
        jedis.rpush("jszahz", "PT-GUARDIANCITIZENIDNO-监护人身份证号");
        jedis.rpush("jszahz", "PT-GUARDIANNAME-监护人姓名");
        jedis.rpush("jszahz", "PT-GUARDIANCONTACT-监护人联系方式");
        jedis.rpush("jszahz", "PT-FIRSTATTACKDATE-初次发病日期");
        jedis.rpush("jszahz", "DICT-CURRENTDIAGNOSTICTYPE|CURRENTDIAGNOSTICTYPEID-mqzdlx|目前诊断类型");
        jedis.rpush("jszahz", "RADIO-TROUBLEHISTORY-是否有肇事肇祸史");
        jedis.rpush("jszahz", "PT-TROUBLENUMBER-肇事肇祸次数");
        jedis.rpush("jszahz", "PT-LASTTROUBLEDATE-上次肇事肇祸日期");
        jedis.rpush("jszahz", "DICT-CURRENTRISKRATING|CURRENTRISKRATINGID-mqwxxpgdj|目前危险性评等级");
        jedis.rpush("jszahz", "DICT-TREATMENTSITUATION|TREATMENTSITUATIONID-zlqk|治疗情况");
        jedis.rpush("jszahz", "PT-HOSPITALNAME-治疗医院名称");
        jedis.rpush("jszahz", "DICT-HOSPITALIZATIONREASONS|HOSPITALIZATIONREASONSID-sszyzlyy|实施治疗住院原因");
        jedis.rpush("jszahz", "PT-REHABILITATIONINSTITUTIONNAME-康复训练机构名称");
        jedis.rpush("jszahz", "DICT-PARTICIPATIONMANAGEMENT|PARTICIPATIONMANAGEMENTID-cyglry|参与管理人员");
        jedis.rpush("jszahz", "DICT-HELPINGSITUATION|HELPINGSITUATIONID-bfqk|帮扶情况");

        jedis.del("xdry");
        jedis.rpush("xdry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("xdry", "PT-NAME-姓名");
        jedis.rpush("xdry", "PT-USEDNAME-曾用名");
        jedis.rpush("xdry", "PT-ORG_NAME-所属网格");
        jedis.rpush("xdry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("xdry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("xdry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("xdry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("xdry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("xdry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("xdry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("xdry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("xdry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("xdry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("xdry", "PT-OCCUPATION-职业");
        jedis.rpush("xdry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("xdry", "PT-CONTACT-联系方式");
        jedis.rpush("xdry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("xdry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("xdry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("xdry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("xdry", "PT-FIRSTFINDDATE-初次发现日期");
        jedis.rpush("xdry", "DICT-CONTROLSITUATION|CONTROLSITUATIONID-gkqk|管控情况");
        jedis.rpush("xdry", "PT-CONTROLPERSONNAME-管控人姓名");
        jedis.rpush("xdry", "PT-CONTROLPERSONCONTACT-管控人联系方式");
        jedis.rpush("xdry", "PT-HELPINGSITUATION-帮扶情况");
        jedis.rpush("xdry", "PT-HELPINGPERSONNAME-帮扶人姓名");
        jedis.rpush("xdry", "PT-HELPINGPERSONCONTACT-帮扶人联系方式");
        jedis.rpush("xdry", "RADIO-CRIMEHISTORY-是否有犯罪史");
        jedis.rpush("xdry", "PT-CRIMESITUATION-犯罪情况");
        jedis.rpush("xdry", "DICT-DRUGREASON|DRUGREASONID-xdyy|吸毒原因");
        jedis.rpush("xdry", "DICT-DRUGCONSEQUENCES|DRUGCONSEQUENCESID-xdhg|吸毒后果");

        jedis.del("zdsfry");
        jedis.rpush("zdsfry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("zdsfry", "PT-NAME-姓名");
        jedis.rpush("zdsfry", "PT-USEDNAME-曾用名");
        jedis.rpush("zdsfry", "PT-ORG_NAME-所属网格");
        jedis.rpush("zdsfry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("zdsfry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("zdsfry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("zdsfry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("zdsfry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("zdsfry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("zdsfry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("zdsfry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("zdsfry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("zdsfry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("zdsfry", "PT-OCCUPATION-职业");
        jedis.rpush("zdsfry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("zdsfry", "PT-CONTACT-联系方式");
        jedis.rpush("zdsfry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("zdsfry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("zdsfry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("zdsfry", "PT-PETITIONSTATUS-上访状态");
        jedis.rpush("zdsfry", "PT-PETITIONCLASS-上访类型分类");
        jedis.rpush("zdsfry", "PT-PETITIONTYPE-上访类型");
        jedis.rpush("zdsfry", "PT-PETITIONCONTENT-上访原因");

        jedis.del("azbwxry");
        jedis.rpush("azbwxry", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("azbwxry", "PT-NAME-姓名");
        jedis.rpush("azbwxry", "PT-USEDNAME-曾用名");
        jedis.rpush("azbwxry", "PT-ORG_NAME-所属网格");
        jedis.rpush("azbwxry", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("azbwxry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("azbwxry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("azbwxry", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("azbwxry", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("azbwxry", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("azbwxry", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("azbwxry", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("azbwxry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("azbwxry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("azbwxry", "PT-OCCUPATION-职业");
        jedis.rpush("azbwxry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("azbwxry", "PT-CONTACT-联系方式");
        jedis.rpush("azbwxry", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("azbwxry", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("azbwxry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("azbwxry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("azbwxry", "DICT-INFECTIONROUTE|INFECTIONROUTEID-grtj|感染途径");
        jedis.rpush("azbwxry", "RADIO-CRIMEHISTORY-是否有违法犯罪史");
        jedis.rpush("azbwxry", "PT-CRIMESITUATION-违法犯罪情况");
        jedis.rpush("azbwxry", "DICT-CASETYPE|CASETYPEID-ajlb|案件类别");
        jedis.rpush("azbwxry", "DICT-CONCERNTYPE|CONCERNTYPEID-gzlx|关注类型");
        jedis.rpush("azbwxry", "PT-HELPINGSITUATION-帮扶情况");
        jedis.rpush("azbwxry", "PT-HELPINGPERSONNAME-帮扶人姓名");
        jedis.rpush("azbwxry", "PT-HELPINGPERSONCONTACT-帮扶人联系方式");
        jedis.rpush("azbwxry", "DICT-ADMITTEDCONDITION|ADMITTEDCONDITIONID-szqk|收治情况");
        jedis.rpush("azbwxry", "PT-INSTITUTIONNAME-收治机构名称");
        jedis.rpush("azbwxry", "DICT-INSTITUTIONLEVEL|INSTITUTIONLEVELID-szjjsscj|收治机构层级");

        jedis.del("zdqsn");
        jedis.rpush("zdqsn", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("zdqsn", "PT-NAME-姓名");
        jedis.rpush("zdqsn", "PT-USEDNAME-曾用名");
        jedis.rpush("zdqsn", "PT-ORG_NAME-所属网格");
        jedis.rpush("zdqsn", "PT-POPULATIONTYPE-实口类型");
        jedis.rpush("zdqsn", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("zdqsn", "PT-BIRTHDATE-出生日期");
        jedis.rpush("zdqsn", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("zdqsn", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("zdqsn", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("zdqsn", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("zdqsn", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("zdqsn", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("zdqsn", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("zdqsn", "PT-OCCUPATION-职业");
        jedis.rpush("zdqsn", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("zdqsn", "PT-CONTACT-联系方式");
        jedis.rpush("zdqsn", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("zdqsn", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("zdqsn", "PT-PRESENTPLACE-现住地");
        jedis.rpush("zdqsn", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("zdqsn", "DICT-PERSONNELTYPE|PERSONNELTYPEID-rylx|人员类型");
        jedis.rpush("zdqsn", "DICT-FAMILYSITUATION|FAMILYSITUATIONID-jtqk|家庭情况");
        jedis.rpush("zdqsn", "PT-GUARDIANCITIZENIDNO-监护人身份证号");
        jedis.rpush("zdqsn", "PT-GUARDIANNAME-监护人姓名");
        jedis.rpush("zdqsn", "DICT-GUARDIANRELATIONSHIP|GUARDIANRELATIONSHIPID-yhzgx|与监护人关系");
        jedis.rpush("zdqsn", "PT-GUARDIANCONTACT-监护人联系方式");
        jedis.rpush("zdqsn", "PT-GUARDIANADRESSDETAILS-监护人居住详址");
        jedis.rpush("zdqsn", "RADIO-ISCRIME-是否违法犯罪");
        jedis.rpush("zdqsn", "PT-CRIMESITUATION-违法犯罪情况");
        jedis.rpush("zdqsn", "PT-HELPINGPERSONNAME-帮扶人姓名");
        jedis.rpush("zdqsn", "PT-HELPINGPERSONCONTACT-帮扶人联系方式");
        jedis.rpush("zdqsn", "DICT-HELPINGMEANS|HELPINGMEANSID-bfsd|帮扶手段");
        jedis.rpush("zdqsn", "PT-HELPINGSITUATION-帮扶情况");

        jedis.del("jwry");
        jedis.rpush("jwry", "PT-FOREIGNFIRSTNAME-外文姓");
        jedis.rpush("jwry", "PT-FOREIGNNAME-外文名");
        jedis.rpush("jwry", "PT-CHINESENAME-中文姓名");
        jedis.rpush("jwry", "PT-ORG_NAME-所属网格");
        jedis.rpush("jwry", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("jwry", "PT-BIRTHDATE-出生日期");
        jedis.rpush("jwry", "DICT-NATIONALITY|NATIONALITYID-gj|国籍(地区)");
        jedis.rpush("jwry", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("jwry", "DICT-CERTIFICATECODE|CERTIFICATEID-zjdm|证件代码");
        jedis.rpush("jwry", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("jwry", "PT-CERTIFICATEVALIDITYFROM-证件有效期开始时间");
        jedis.rpush("jwry", "PT-CERTIFICATEVALIDITYTO-证件有效期结束时间");
        jedis.rpush("jwry", "PT-CONTACT-联系方式");
        jedis.rpush("jwry", "DICT-PURPOSEOFCHINA|PURPOSEOFCHINAID-lhmd|来华目的");
        jedis.rpush("jwry", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("jwry", "PT-OCCUPATION-职业");
        jedis.rpush("jwry", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("jwry", "PT-PRESENTPLACE-现住地");
        jedis.rpush("jwry", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("jwry", "PT-ARRIVALDATE-抵达日期");
        jedis.rpush("jwry", "PT-ESTIMATEDDEPARTUREDATE-预计离开日期");
        jedis.rpush("jwry", "RADIO-ISKEYPERSON-是否重点关注人员");
        jedis.rpush("jwry", "PT-REMARK-备注");
        jedis.rpush("jwry", "DICT-CONCERNDEGREE|CONCERNDEGREEID-gzcd|关注程度");
        jedis.rpush("jwry", "DICT-ATTENTIONTYPE|ATTENTIONTYPEID-zdgzrylx|重点关注人员类型");
        jedis.rpush("jwry", "PT-CONCERNREASON-关注原因");

        jedis.del("syfw");
        jedis.rpush("syfw", "PT-ORG_NAME-所属网格");
        jedis.rpush("syfw", "PT-HOUSECODE-房屋编号");
        jedis.rpush("syfw", "PT-HOUSEADDRESS-房屋地址");
        jedis.rpush("syfw", "DICT-BUILDINGPURPOSE|BUILDINGPURPOSEID-jzyt|建筑用途");
        jedis.rpush("syfw", "PT-BUILDINGAREA-建筑面积(平方米)");
        jedis.rpush("syfw", "DICT-CERTIFICATECODE|CERTIFICATEID-zjdm|证件代码");
        jedis.rpush("syfw", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("syfw", "PT-OWNERNAME-房主姓名");
        jedis.rpush("syfw", "PT-OWNERCONTACT-房主联系方式");
        jedis.rpush("syfw", "PT-OWNERADDRESSDETAILS-房主现居详址");
        jedis.rpush("syfw", "RADIO-ISRENTALHOUSE-是否出租房");
        jedis.rpush("syfw", "PT-PERSONNUMBER-人员数量");
        jedis.rpush("syfw", "DICT-RENTALUSE|RENTALUSEID-czyt|出租用途");
        jedis.rpush("syfw", "DICT-HIDDENDANGERTYPE|HIDDENDANGERTYPEID-yhlx|隐患类型");
        jedis.rpush("syfw", "PT-TENANTCITIZENSHIPNO-承租人身份号码");
        jedis.rpush("syfw", "PT-TENANTNAME-承租人姓名");
        jedis.rpush("syfw", "PT-TENANTCONTACT-承租人联系方式");

        jedis.del("czf");
        jedis.rpush("czf", "PT-ORG_NAME-所属网格");
        jedis.rpush("czf", "PT-HOUSECODE-房屋编号");
        jedis.rpush("czf", "PT-HOUSEADDRESS-房屋地址");
        jedis.rpush("czf", "DICT-BUILDINGPURPOSE|BUILDINGPURPOSEID-jzyt|建筑用途");
        jedis.rpush("czf", "PT-BUILDINGAREA-建筑面积(平方米)");
        jedis.rpush("czf", "DICT-CERTIFICATECODE|CERTIFICATEID-zjdm|证件代码");
        jedis.rpush("czf", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("czf", "PT-OWNERNAME-房主姓名");
        jedis.rpush("czf", "PT-OWNERCONTACT-房主联系方式");
        jedis.rpush("czf", "PT-OWNERADDRESSDETAILS-房主现居详址");
        jedis.rpush("czf", "RADIO-ISRENTALHOUSE-是否出租房");
        jedis.rpush("czf", "PT-PERSONNUMBER-人员数量");
        jedis.rpush("czf", "DICT-RENTALUSE|RENTALUSEID-czyt|出租用途");
        jedis.rpush("czf", "DICT-HIDDENDANGERTYPE|HIDDENDANGERTYPEID-yhlx|隐患类型");
        jedis.rpush("czf", "PT-TENANTCITIZENSHIPNO-承租人身份号码");
        jedis.rpush("czf", "PT-TENANTNAME-承租人姓名");
        jedis.rpush("czf", "PT-TENANTCONTACT-承租人联系方式");

        jedis.del("lygl");
        jedis.rpush("lygl", "PT-ORG_NAME-所属网格");
        jedis.rpush("lygl", "PT-BUILDINGNAME-楼宇名称");
        jedis.rpush("lygl", "PT-BUILDINGADDRESS-楼宇地址");
        jedis.rpush("lygl", "PT-OWNER-业主");
        jedis.rpush("lygl", "PT-RESPONSIBLEPERSON-负责人");
        jedis.rpush("lygl", "PT-PHONE-联系电话");
        jedis.rpush("lygl", "DICT-BUILDINGSTRUCTURES|BUILDINGSTRUCTURESID-jzjg|建筑结构");
        jedis.rpush("lygl", "RADIO-ISLAYOUT-是否有楼宇布局");
        jedis.rpush("lygl", "DICT-BUILDINGTYPE|BUILDINGTYPEID-lylx|楼宇类型");

        jedis.del("czrk");
        jedis.rpush("czrk", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("czrk", "PT-NAME-姓名");
        jedis.rpush("czrk", "PT-USEDNAME-曾用名");
        jedis.rpush("czrk", "PT-ORG_NAME-所属网络");
        jedis.rpush("czrk", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("czrk", "PT-BIRTHDATE-出生日期");
        jedis.rpush("czrk", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("czrk", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("czrk", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("czrk", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("czrk", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("czrk", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("czrk", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("czrk", "PT-OCCUPATION-职业");
        jedis.rpush("czrk", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("czrk", "PT-CONTACT-联系方式");
        jedis.rpush("czrk", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("czrk", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("czrk", "PT-PRESENTPLACE-现住地");
        jedis.rpush("czrk", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("czrk", "PT-PEOPLETYPE-人员类别");

        jedis.del("hjjt");
        jedis.rpush("hjjt", "PT-ACCOUNTNUMBER-户号");
        jedis.rpush("hjjt", "PT-IDCARDNO-户主身份证号");
        jedis.rpush("hjjt", "PT-HOUSEHOLDNAME-户主姓名");
        jedis.rpush("hjjt", "PT-ORG_NAME-所属网格");
        jedis.rpush("hjjt", "PT-HOMEPHONE-家庭电话");
        jedis.rpush("hjjt", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("hjjt", "PT-MOBILENUMBER-手机号码");
        jedis.rpush("hjjt", "PT-TELEPHONE-固定电话");
        jedis.rpush("hjjt", "PT-CURRENTADDRESS-户主住址");

        jedis.del("zzjg");
        jedis.rpush("zzjg", "PT-ORG_NAME-所属网格");
        jedis.rpush("zzjg", "PT-COMPMANAGENAME-综治机构名称");
        jedis.rpush("zzjg", "DICT-COMPMANAGETYPE|COMPMANAGETYPEID-jglx|综治机构类型");
        jedis.rpush("zzjg", "DICT-COMPMANAGELEVEL|COMPMANAGELEVELID-jgcj|综治机构层级");
        //jedis.rpush("zzjg", "PT-PERSONNUMBER-人员数量");

        jedis.del("qfqzzz");
        jedis.rpush("qfqzzz", "PT-ORG_NAME-所属网格");
        jedis.rpush("qfqzzz", "PT-QFQZORGNAME-群防群治组织名称");
        jedis.rpush("qfqzzz", "DICT-QFQZORGTYPE|QFQZORGTYPEID-qfzzlx|群防群治组织类型");
        jedis.rpush("qfqzzz", "DICT-QFQZORGLEVEL|QFQZORGLEVELID-cj|群防群治组织层级");
        jedis.rpush("qfqzzz", "PT-GUIDANCEDEPARTMENT-业务指导部门");
        jedis.rpush("qfqzzz", "PT-PERSONNUMBER-人员数量");
        jedis.rpush("qfqzzz", "PT-MAINFUNCTION-主要职能");

        jedis.del("qfqzdw");
        jedis.rpush("qfqzdw", "PT-ORG_NAME-所属网格");
        //jedis.rpush("qfqzdw", "PT-QFQZZZ_ORGNAME-群防群治组织名称");
        jedis.rpush("qfqzdw", "PT-NAME-姓名");
        jedis.rpush("qfqzdw", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("qfqzdw", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("qfqzdw", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("qfqzdw", "DICT-CERTIFICATECODE|CERTIFICATEID-zjdm|证件代码");
        jedis.rpush("qfqzdw", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("qfqzdw", "PT-BIRTHDATE-出生日期");
        jedis.rpush("qfqzdw", "PT-POST-职务");
        jedis.rpush("qfqzdw", "DICT-SPECIALTY|SPECIALTYID-zytc|专业特长");
        jedis.rpush("qfqzdw", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("qfqzdw", "PT-PHONENUMBER-手机号码");
        jedis.rpush("qfqzdw", "PT-FIXEDTELEPHONE-固定电话");

        jedis.del("wghjs");
        jedis.rpush("wghjs", "PT-ORG_NAME-所属网格");
        jedis.rpush("wghjs", "PT-GRIDNAME-网格名称");
        jedis.rpush("wghjs", "PT-GRIDHEADNAME-网格长姓名");
        jedis.rpush("wghjs", "PT-GRIDMEMBERNAME-网格员姓名");
        jedis.rpush("wghjs", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("wghjs", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("wghjs", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("wghjs", "PT-BIRTHDATE-出生日期");
        jedis.rpush("wghjs", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("wghjs", "PT-PHONENUMBER-手机号码");
        jedis.rpush("wghjs", "PT-FIXEDTELEPHONE-固定电话");
        jedis.rpush("wghjs", "PT-GRIDMEMBERSNUMBER-网格员数量");
        jedis.rpush("wghjs", "PT-GRIDNUMBER-网格户数");
        jedis.rpush("wghjs", "PT-GRIDAREA-网格面积(平方米)");

        jedis.del("ztdasj");
        jedis.rpush("ztdasj", "PT-ORG_NAME-所属网格");
        jedis.rpush("ztdasj", "PT-CASENAME-案(事)件名称");
        jedis.rpush("ztdasj", "PT-OCCURRENCEDATE-发生日期");
        jedis.rpush("ztdasj", "PT-OCCURRENCEPLACE-发生地");
        jedis.rpush("ztdasj", "PT-OCCURRENCEDETAILS-发生地详址");
        jedis.rpush("ztdasj", "DICT-CASECLASSIFICATION|CASECLASSIFICATIONID-asjfj|案(事)件分级");
        jedis.rpush("ztdasj", "DICT-CASETYPE|CASETYPEID-asjlx|案(事)件类型");
        jedis.rpush("ztdasj", "PT-CASESITUATION-案(事)件情况");

        jedis.del("ldzrz");
        jedis.rpush("ldzrz", "PT-ORG_NAME-所属网格");
        jedis.rpush("ldzrz", "PT-IMPLEMENTEDAREA-被实施地区");
        jedis.rpush("ldzrz", "DICT-IMPLEMENTEDAREALEVEL|IMPLEMENTEDAREALEVELID-zxcj|被实施地区层级");
        jedis.rpush("ldzrz", "PT-SUBJECTNAME-实施主体名称");
        jedis.rpush("ldzrz", "DICT-SUBJECTLEVEL|SUBJECTLEVELID-zxcj|实施主体层级");
        jedis.rpush("ldzrz", "DICT-POLICYCATEGORY|POLICYCATEGORYID-zczl|政策种类");

        jedis.del("slwxxzx");
        jedis.rpush("slwxxzx", "PT-ORG_NAME-所属网格");
        jedis.rpush("slwxxzx", "PT-NETWORKCENTERNAME-视联中心名称");
        jedis.rpush("slwxxzx", "PT-NETWORKCENTERCONTACT-视联中心联系方式");
        jedis.rpush("slwxxzx", "DICT-NETWORKCENTERLEVEL|NETWORKCENTERLEVELID-zxcj|视联中心层级");
        jedis.rpush("slwxxzx", "PT-INCHARGEPERSONNAME-视联中心负责人");
        jedis.rpush("slwxxzx", "PT-FULLTIMESTAFFNUMBER-专职人员数量");
        jedis.rpush("slwxxzx", "PT-OFFICESPACE-办公房面积(平方米)");
        jedis.rpush("slwxxzx", "PT-ANNUALOPERATINGEXPENSES-年度运行经费(元)");
        jedis.rpush("slwxxzx", "PT-CAMERANUMBER-联网监控摄像机数量");
        jedis.rpush("slwxxzx", "RADIO-ISONDUTYFULLDAY-是否24小时值守");
        jedis.rpush("slwxxzx", "PT-LOCATION-所在地");
        jedis.rpush("slwxxzx", "PT-LOCATIONDETAILS-所在地详址");

        jedis.del("zzzx");
        jedis.rpush("zzzx", "PT-ORG_NAME-所属网格");
        jedis.rpush("zzzx", "PT-COMPCENTERNAME-综治中心名称");
        jedis.rpush("zzzx", "PT-COMPCENTERCONTACT-综治中心联系方式");
        jedis.rpush("zzzx", "DICT-COMPCENTERLEVEL|COMPCENTERLEVELID-zxcj|综治中心层级");
        jedis.rpush("zzzx", "PT-INCHARGEPERSONNAME-负责人姓名");
        jedis.rpush("zzzx", "PT-INCHARGEPERSONCONTACT-负责人联系方式");
        jedis.rpush("zzzx", "PT-COMPONENT-组成单位");
        jedis.rpush("zzzx", "PT-LOCATION-所在地");
        jedis.rpush("zzzx", "PT-LOCATIONDETAILS-所在地详址");

        jedis.del("zzdw");
        jedis.rpush("zzdw", "PT-ORG_NAME-所属网格");
        jedis.rpush("zzdw", "PT-NAME-姓名");
        jedis.rpush("zzdw", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("zzdw", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("zzdw", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("zzdw", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("zzdw", "PT-BIRTHDATE-出生日期");
        jedis.rpush("zzdw", "DICT-ZZDWLEVEL|ZZDWLEVELID-ryjb|级别");
        jedis.rpush("zzdw", "DICT-POST|POSTID-zw|职务");
        jedis.rpush("zzdw", "DICT-SPECIALTY|SPECIALTYID-zytc|专业特长");
        jedis.rpush("zzdw", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("zzdw", "PT-PHONENUMBER-手机号码");
        jedis.rpush("zzdw", "PT-FIXEDTELEPHONE-固定电话");

        jedis.del("cxsqggaqspjk");
        jedis.rpushx("cxsqggaqspjk", "PT-ORG_NAME-所属网格");
        jedis.rpushx("cxsqggaqspjk", "PT-COMMUNITYNAME-城乡社区名称");
        jedis.rpushx("cxsqggaqspjk", "PT-COMMUNITYCONTACT-社区联系方式");
        jedis.rpushx("cxsqggaqspjk", "PT-COMMUNITYSPACE-社区面积(平方米)");
        jedis.rpushx("cxsqggaqspjk", "PT-COMMUNITYPERSONNUMBER-城乡社区人口");
        jedis.rpushx("cxsqggaqspjk", "PT-PUBLICSECURITYCAMERANUMBER-安全监控摄像机总数");
        jedis.rpushx("cxsqggaqspjk", "PT-HDCAMERANUMBER-高清摄像机数量");
        jedis.rpushx("cxsqggaqspjk", "PT-TOWNSHIPNETWORKCAMERANUMBER-乡镇联网摄像机数量");
        jedis.rpushx("cxsqggaqspjk", "PT-DUTYFULLDAYCAMERANUMBER-24小时摄像机数量");
        jedis.rpushx("cxsqggaqspjk", "PT-PERSQUAREKMCAMERANUMBER-每平方公里摄像机数量");
        jedis.rpushx("cxsqggaqspjk", "PT-PERHUNDREDPEOPLECAMERANUMBER-每百人摄像机数量");

        jedis.del("ldz");
        jedis.rpush("ldz", "PT-ORG_NAME-所属网格");
        jedis.rpush("ldz", "PT-COMMUNITYNAME-小区(单位)民称");
        jedis.rpush("ldz", "PT-BUILDINGNAME-楼栋名称");
        jedis.rpush("ldz", "PT-BUILDINGAREA-建筑面积(平方米)");
        jedis.rpush("ldz", "PT-LAYERNUMBER-层数");
        jedis.rpush("ldz", "PT-UNITNUMBER-单元数");
        jedis.rpush("ldz", "PT-BUILDINGHOUSEHOLDSNUMBER-楼栋户数");
        jedis.rpush("ldz", "PT-BUILDINGPEOPLENUMBER-楼栋人数");
        jedis.rpush("ldz", "PT-BUILDINGHEADNUMBER-楼栋长姓名");
        jedis.rpush("ldz", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("ldz", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("ldz", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("ldz", "PT-BIRTHDATE-出生日期");
        jedis.rpush("ldz", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("ldz", "PT-PHONENUMBER-手机号码");
        jedis.rpush("ldz", "PT-FIXEDTELEPHONE-固定电话");
        jedis.rpush("ldz", "PT-LOCATION-所在地");
        jedis.rpush("ldz", "PT-LOCATIONDETAILS-所在地详址");

        jedis.del("fwtd");
        jedis.rpush("fwtd", "PT-ORG_NAME-所属网格");
        jedis.rpush("fwtd", "DICT-TEAMTYPE|TEAMTYPEID-fwtdlx|团队类型");
        jedis.rpush("fwtd", "PT-NAME-团队名称");
        jedis.rpush("fwtd", "PT-SIMPLEPINYIN-拼音简码");
        jedis.rpush("fwtd", "PT-FULLPINYIN-拼音全拼");
        jedis.rpush("fwtd", "PT-BUILDDATE-成立时间");
        jedis.rpush("fwtd", "PT-REMARK-备注");

        jedis.del("fwcy");
        jedis.rpush("fwcy", "PT-ORG_NAME-所属网格");
        jedis.rpush("fwcy", "PT-NAME-姓名");
        jedis.rpush("fwcy", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("fwcy", "PT-MOBILE-手机");
        jedis.rpush("fwcy", "PT-HOMEPHONE-家庭电话");
        jedis.rpush("fwcy", "PT-JOB-职位");
        jedis.rpush("fwcy", "PT-SIMPLEPINYIN-拼音简码");
        jedis.rpush("fwcy", "PT-FULLPINYIN-拼音全拼");
        jedis.rpush("fwcy", "PT-BIRTHDAY-出生年份");
        jedis.rpush("fwcy", "PT-UNIT-所在单位");
        jedis.rpush("fwcy", "PT-UNITJOB-所在单位职务");
        jedis.rpush("fwcy", "PT-REMARK-备注");

        jedis.del("fwjl");
        jedis.rpush("fwjl", "PT-ORG_NAME-所属网格");
        jedis.rpush("fwjl", "PT-OCCURDATE-服务时间");
        jedis.rpush("fwjl", "PT-OCCURPLACE-服务地点");
        jedis.rpush("fwjl", "PT-SERVICEMEMBERS-服务成员");
        jedis.rpush("fwjl", "PT-SERVICEJOINERS-其他参与人员");
        jedis.rpush("fwjl", "PT-SERVICEOBJECTS-服务对象");
        jedis.rpush("fwjl", "PT-SERVICECONTENT-服务内容");

        jedis.del("fgyzjjzz");
        jedis.rpush("fgyzjjzz", "PT-ORG_NAME-所属网格");
        jedis.rpush("fgyzjjzz", "PT-BUSINESSLICENSENO-工商执照注册号");
        jedis.rpush("fgyzjjzz", "PT-ENTERPRISENAME-企业名称");
        jedis.rpush("fgyzjjzz", "DICT-ENTERPRISETYPE|ENTERPRISETYPEID-qylb|企业类别");
        jedis.rpush("fgyzjjzz", "PT-ENTERPRISEADDRESS-企业地址");
        jedis.rpush("fgyzjjzz", "PT-ENTERPRISECONTACT-企业联系方式");
        jedis.rpush("fgyzjjzz", "PT-EMPLOYEESNUMBER-企业员工数");
        jedis.rpush("fgyzjjzz", "DICT-REPRESENTATIVECERTIFICATECODE|REPRESENTATIVECERTIFICATEID-zjdm|法定代表证件代码");
        jedis.rpush("fgyzjjzz", "PT-REPRESENTATIVECERTIFICATENO-法定代表证件号码");
        jedis.rpush("fgyzjjzz", "PT-REPRESENTATIVENAME-法定代表人姓名");
        jedis.rpush("fgyzjjzz", "PT-REPRESENTATIVECONTACT-法定代表联系方式");
        jedis.rpush("fgyzjjzz", "PT-SECURITYINCHARGENAME-治保负责人姓名");
        jedis.rpush("fgyzjjzz", "PT-SECURITYINCHARGECONTACT-治保负责人联系方式");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAZARDOUSENTERPRISE-是否危化企业");
        jedis.rpush("fgyzjjzz", "DICT-SECURITYHAZARDTYPE|SECURITYHAZARDTYPEID-aqyhlx|安全隐患类型");
        jedis.rpush("fgyzjjzz", "DICT-CONCERNDEGREE|CONCERNDEGREEID-gzcd|关注程度");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAVEESTABLISHCPCORG-是否具备建立组织条件");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAVECPCORG-是否有中共党组织");
        jedis.rpush("fgyzjjzz", "PT-CPCMEMBERSNUMBER-中共党员数量");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAVELABOURUNION-是否有工会");
        jedis.rpush("fgyzjjzz", "PT-LABOURUNIONMEMBERSNUMBER-工会会员数量");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAVEYOUTHLEAGUEORG-是否有共青团组织");
        jedis.rpush("fgyzjjzz", "PT-YOUTHLEAGUEMEMBERSNUMBER-共青团团员数量");
        jedis.rpush("fgyzjjzz", "RADIO-ISHAVEWOMENFEDERATIONS-是否有妇联组织");
        jedis.rpush("fgyzjjzz", "PT-WOMENNUMBER-妇女数量");

        jedis.del("shzz");
        jedis.rpush("shzz", "PT-ORG_NAME-所属网格");
        jedis.rpush("shzz", "PT-UNIFORMSOCIALCREDITCODE-统一社会信用代码");
        jedis.rpush("shzz", "PT-REGISTRATIONNO-登记证号");
        jedis.rpush("shzz", "PT-SOCIALORGNAME-社会组织名称");
        jedis.rpush("shzz", "PT-REGISTRATIONADMINISTRATIONCODE-登记管理机关代码");
        jedis.rpush("shzz", "PT-REPRESENTATIVENAME-法定代表人姓名");
        jedis.rpush("shzz", "PT-RESIDENCE-住所");
        jedis.rpush("shzz", "PT-APPROVALDATE-批准日期");
        jedis.rpush("shzz", "DICT-SOCIALORGTYPE|SOCIALORGTYPEID-shzzlx|社会组织类型");
        jedis.rpush("shzz", "STATE-STATE-状态");
        jedis.rpush("shzz", "DICT-INCHARGECERTIFICATECODE|INCHARGECERTIFICATECODEID-zjdm|负责人证件代码");
        jedis.rpush("shzz", "PT-INCHARGECERTIFICATENO-负责人证件号码");
        jedis.rpush("shzz", "PT-INCHARGENAME-负责人姓名");
        jedis.rpush("shzz", "PT-INCHARGECONTACT-负责人联系方式");
        jedis.rpush("shzz", "PT-OFFICEADDRESS-办公地址");
        jedis.rpush("shzz", "PT-SECURITYINCHARGENAME-治保负责人姓名");
        jedis.rpush("shzz", "PT-SECURITYINCHARGECONTACT-治保负责人联系方式");
        jedis.rpush("shzz", "DICT-CONCERNDEGREE|CONCERNDEGREEID-gzcd|关注程度");
        jedis.rpush("shzz", "RADIO-ISHAVEESTABLISHCPCORG-是否具备建立组织条件");
        jedis.rpush("shzz", "RADIO-ISHAVECPCORG-是否有中共党组织");
        jedis.rpush("shzz", "PT-CPCMEMBERSNUMBER-中共党员数量");
        jedis.rpush("shzz", "RADIO-ISHAVELABOURUNION-是否有工会");
        jedis.rpush("shzz", "PT-LABOURUNIONMEMBERSNUMBER-工会会员数量");
        jedis.rpush("shzz", "RADIO-ISHAVEYOUTHLEAGUEORG-是否有共青团组织");
        jedis.rpush("shzz", "PT-YOUTHLEAGUEMEMBERSNUMBER-共青团团员数量");
        jedis.rpush("shzz", "RADIO-ISHAVEWOMENFEDERATIONS-是否有妇联组织");
        jedis.rpush("shzz", "PT-WOMENNUMBER-妇女数量");
        jedis.rpush("shzz", "PT-FUNDSSOURCE-资金来源");
        jedis.rpush("shzz", "RADIO-ISHAVEABROADBACKGROUND-是否有境外背景");

        jedis.del("zddqpczz");
        jedis.rpush("zddqpczz", "PT-ORG_NAME-所属网格");
        jedis.rpush("zddqpczz", "PT-PUBLICSECURITYKSYAREA-治安重点地区");
        jedis.rpush("zddqpczz", "DICT-PUBLICSECURITYPROBLEMS|PUBLICSECURITYPROBLEMSID-zatcwt|治安突出问题");
        jedis.rpush("zddqpczz", "DICT-INVOLVEAREATYPE|INVOLVEAREATYPEID-sjqylx|涉及区域类型");
        jedis.rpush("zddqpczz", "PT-INVOLVEAREA-涉及区域范围");
        jedis.rpush("zddqpczz", "PT-REMEDIATIONLEADINGUNIT-整治牵头单位");
        jedis.rpush("zddqpczz", "PT-REGULATIONPARTICIPATIONUNIT-整治参与单位");
        jedis.rpush("zddqpczz", "PT-LEADINGUNITINCHARGENAME-牵头单位负责人姓名");
        jedis.rpush("zddqpczz", "PT-LEADINGUNITINCHARGECONTACT-牵头单位负责人联系方式");
        jedis.rpush("zddqpczz", "PT-RECTIFICATIONTIMELIMIT-整改时限");
        jedis.rpush("zddqpczz", "PT-CRACKEDCRIMINALCASESNUMBER-期间破获刑事案件数");
        jedis.rpush("zddqpczz", "PT-INVESTIGATIONSECURICASESNUMBER-期间查处治安案件数");
        jedis.rpush("zddqpczz", "PT-REMEDIATIONSITUATION-整治情况");
        jedis.rpush("zddqpczz", "DICT-EFFECTIVENESSEVALUATION|EFFECTIVENESSEVALUATIONID-xgpg|效果评估");

        jedis.del("jdwlaqgl");
        jedis.rpush("jdwlaqgl", "PT-ORG_NAME-所属网格");
        jedis.rpush("jdwlaqgl", "PT-BUSINESSLICENSENO-工商执照注册号");
        jedis.rpush("jdwlaqgl", "PT-DELIVERYENTERPRISENAME-寄递物流企业名称");
        jedis.rpush("jdwlaqgl", "PT-LOCATION-所在地");
        jedis.rpush("jdwlaqgl", "PT-ENTERPRISEADDRESSDETAILS-企业详址");
        jedis.rpush("jdwlaqgl", "PT-ENTERPRISECONTACT-企业联系方式");
        jedis.rpush("jdwlaqgl", "PT-ENTERPRISEINCHARGENAME-企业负责人姓名");
        jedis.rpush("jdwlaqgl", "PT-ENTERPRISEINCHARGECONTACT-企业负责人联系方式");
        jedis.rpush("jdwlaqgl", "DICT-REGISTRATIONTYPE|REGISTRATIONTYPEID-djzclx|登记注册类型");
        jedis.rpush("jdwlaqgl", "DICT-HOLDINGSITUATION|HOLDINGSITUATIONID-kgqk|控股情况");
        jedis.rpush("jdwlaqgl", "DICT-BUSINESSSCOPE|BUSINESSSCOPEID-jyfw|经营范围");
        jedis.rpush("jdwlaqgl", "DICT-ENTERPRISETYPE|ENTERPRISETYPEID-wlqylx|企业类型");
        jedis.rpush("jdwlaqgl", "PT-SERVICEBRAND-服务品牌");
        jedis.rpush("jdwlaqgl", "PT-EMPLOYEESNUMBER-从业人员数量");
        jedis.rpush("jdwlaqgl", "PT-MONITORCAMERANUMBER-监控摄像机数量");
        jedis.rpush("jdwlaqgl", "PT-XRAYMACHINENUMBER-X光机数量");
        jedis.rpush("jdwlaqgl", "RADIO-ISINSPECTIONSEALINGBOX-是否落实先验视后封箱");
        jedis.rpush("jdwlaqgl", "RADIO-ISDELIVERYREALNAME-是否落实寄递实名制");
        jedis.rpush("jdwlaqgl", "RADIO-ISXRAYMACHINESECURITYCHECK-是否落实X光机安检");

        jedis.del("hlhx");
        jedis.rpush("hlhx", "PT-ORG_NAME-所属网格");
        jedis.rpush("hlhx", "PT-NAME-名称");
        jedis.rpush("hlhx", "DICT-LINETYPE|LINETYPEID-xllx|线路类型");
        jedis.rpush("hlhx", "PT-SUBORDINATEUNITNAME-隶属单位名称");
        jedis.rpush("hlhx", "PT-SUBORDINATEUNITADRESSDETAILS-隶属单位详址");
        jedis.rpush("hlhx", "PT-SUBORDINATEUNITCONTACT-隶属单位联系方式");
        jedis.rpush("hlhx", "PT-UNITINCHARGENAME-隶属单位负责人姓名");
        jedis.rpush("hlhx", "PT-UNITINCHARGECONTACT-隶属单位负责人联系方式");
        jedis.rpush("hlhx", "PT-JURISDICTIONUNITNAME-管辖单位名称");
        jedis.rpush("hlhx", "PT-JURISDICTIONUNITADRESSDETAILS-管辖单位详址");
        jedis.rpush("hlhx", "PT-JURISDICTIONUNITCONTACCT-管辖单位联系方式");
        jedis.rpush("hlhx", "PT-PUTSECURITYINCHARGENAME-分管安全保卫责任人姓名");
        jedis.rpush("hlhx", "PT-PUTSECURITYINCHARGECONTACT-分管安全保卫责任人联系方式");
        jedis.rpush("hlhx", "PT-SECURITYTROUBLESITUATION-治安隐患情况");
        jedis.rpush("hlhx", "DICT-SECURITYTROUBLELEVEL|SECURITYTROUBLELEVELID-gzsjfxdj|治安隐患等级");

        jedis.del("pcqk");
        jedis.rpush("pcqk", "PT-ORG_NAME-所属网格");
        jedis.rpush("pcqk", "PT-RECORDNO-记录编号");
        jedis.rpush("pcqk", "DICT-CHECKTYPE|CHECKTYPEID-jclx|检查类型");
        jedis.rpush("pcqk", "PT-CHECKTIME-检查时间");
        jedis.rpush("pcqk", "PT-SERVICEPERSONNAME-服务人员姓名");
        jedis.rpush("pcqk", "PT-OTHERPERSON-其他参与人员");
        jedis.rpush("pcqk", "PT-CHECKPOSITION-检查部位");
        jedis.rpush("pcqk", "PT-SUGGESTINFO-建议形式");
        jedis.rpush("pcqk", "PT-DANGERINFO-隐患情况");
        jedis.rpush("pcqk", "PT-PREVENTINFO-防范建议");
        jedis.rpush("pcqk", "PT-IMPROVEINFO-整改意见");

        jedis.del("sgqk");
        jedis.rpush("sgqk", "PT-ORG_NAME-所属网格");
        jedis.rpush("sgqk", "PT-NAME-事故名称");
        jedis.rpush("sgqk", "DICT-ACCIDENTTYPE|ACCIDENTTYPEID-sglx|事故类型");
        jedis.rpush("sgqk", "PT-OCCURTIME-发生时间");
        jedis.rpush("sgqk", "PT-PERSONCOUNT-事故发生人数");
        jedis.rpush("sgqk", "PT-LINKNAME-责任人姓名");
        jedis.rpush("sgqk", "PT-LINKTEL-责任人电话");
        jedis.rpush("sgqk", "PT-SUMMARY-摘要");

        jedis.del("sjxlaj");
        jedis.rpush("sjxlaj", "PT-ORG_NAME-所属网格");
        jedis.rpush("sjxlaj", "PT-CASECODE-案(事)件编号");
        jedis.rpush("sjxlaj", "PT-CASENAME-案(事)件名称");
        jedis.rpush("sjxlaj", "PT-OCCURRENTDATE-发生日期");
        jedis.rpush("sjxlaj", "PT-OCCURRENTPLACCE-发生地点");
        jedis.rpush("sjxlaj", "DICT-CASENATURE|CASENATUREID-asjxz|案(事)件性质");
        jedis.rpush("sjxlaj", "PT-CASESITUATION-案(事)件情况");
        jedis.rpush("sjxlaj", "DICT-PRINCIPALCERTIFICATECODE|PRINCIPALCERTIFICATEID-zjdm|主犯(嫌疑人)证件代码");
        jedis.rpush("sjxlaj", "PT-PRINCIPALCERTIFICATENO-主犯(嫌疑人)证件号码");
        jedis.rpush("sjxlaj", "PT-PRINCIPALNAME-主犯(嫌疑人)姓名");
        jedis.rpush("sjxlaj", "PT-ISSOLVECASE-是否破案");
        jedis.rpush("sjxlaj", "PT-THECRIMENUMBER-作案人数");
        jedis.rpush("sjxlaj", "PT-FUGITIVESNUMBER-在逃人数");
        jedis.rpush("sjxlaj", "PT-ARRESTNUMBER-抓捕人数");
        jedis.rpush("sjxlaj", "PT-CASEDETECTIONSITUATION-案件侦破情况");

        jedis.del("majbxx");
        jedis.rpush("majbxx", "PT-ORG_NAME-所属网格");
        jedis.rpush("majbxx", "PT-CASENAME-案件名称");
        jedis.rpush("majbxx", "PT-CASECODE-案件编号");
        jedis.rpush("majbxx", "PT-CASEBEGINDATE-案件发生开始日期");
        jedis.rpush("majbxx", "PT-INVESTIGATIONENDDATE-侦查终结日期");
        jedis.rpush("majbxx", "PT-BRIEFSITUATION-简要情况");

        jedis.del("mafzxyr");
        jedis.rpush("mafzxyr", "PT-MAJBXX_CASECODE-案件编号");
        jedis.rpush("mafzxyr", "PT-ORG_NAME-所属网格");
        jedis.rpush("mafzxyr", "DICT-CERTIFICATECODE|CERTIFICATECODEID-zjdm|证件代码");
        jedis.rpush("mafzxyr", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("mafzxyr", "PT-NAME-姓名");
        jedis.rpush("mafzxyr", "PT-USEDNAME-曾用名");
        jedis.rpush("mafzxyr", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("mafzxyr", "PT-BIRTHDATE-出生日期");
        jedis.rpush("mafzxyr", "DICT-NATIONALITY|NATIONALITYID-gj|国籍(地区)");
        jedis.rpush("mafzxyr", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("mafzxyr", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("mafzxyr", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("mafzxyr", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("mafzxyr", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("mafzxyr", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("mafzxyr", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("mafzxyr", "PT-OCCUPATION-职业");
        jedis.rpush("mafzxyr", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("mafzxyr", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("mafzxyr", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("mafzxyr", "PT-PRESENTPLACE-现住地");
        jedis.rpush("mafzxyr", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");
        jedis.rpush("mafzxyr", "RADIO-ISSEVEREMENTALDISORDERS-是否为精神障碍患者");
        jedis.rpush("mafzxyr", "RADIO-ISJUVENILES-是否为未成年人");
        jedis.rpush("mafzxyr", "RADIO-ISTEENAGERS-是否为青少年");

        jedis.del("mashr");
        jedis.rpush("mashr", "PT-MAJBXX_CASECODE-案件编号");
        jedis.rpush("mashr", "PT-ORG_NAME-所属网格");
        jedis.rpush("mashr", "DICT-CERTIFICATECODE|CERTIFICATECODEID-zjdm|证件代码");
        jedis.rpush("mashr", "PT-CERTIFICATENUMBER-证件号码");
        jedis.rpush("mashr", "PT-NAME-姓名");
        jedis.rpush("mashr", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("mashr", "PT-BIRTHDATE-出生日期");
        jedis.rpush("mashr", "DICT-NATIONALITY|NATIONALITYID-gj|国籍(地区)");
        jedis.rpush("mashr", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("mashr", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("mashr", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("mashr", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("mashr", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("mashr", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("mashr", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("mashr", "PT-OCCUPATION-职业");
        jedis.rpush("mashr", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("mashr", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("mashr", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("mashr", "PT-PRESENTPLACE-现住地");
        jedis.rpush("mashr", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");

        jedis.del("zzldzrz");
        jedis.rpush("zzldzrz", "PT-ORG_NAME-所属网格");
        jedis.rpush("zzldzrz", "PT-IMPLEMENTEDAREA-被实施地区");
        jedis.rpush("zzldzrz", "DICT-IMPLEMENTEDAREALEVEL|IMPLEMENTEDAREALEVELID-zxcj|被实施地区层级");
        jedis.rpush("zzldzrz", "PT-SUBJECTNAME-实施主体名称");
        jedis.rpush("zzldzrz", "DICT-SUBJECTLEVEL|SUBJECTLEVELID-zxcj|实施主体层级");
        jedis.rpush("zzldzrz", "DICT-POLICYCATEGORY|POLICYCATEGORYID-zczl|政策种类");

        jedis.del("cxsqggaqspjk");
        jedis.rpush("cxsqggaqspjk", "PT-ORG_NAME-所属网格");
        jedis.rpush("cxsqggaqspjk", "PT-COMMUNITYNAME-城乡社区名称");
        jedis.rpush("cxsqggaqspjk", "PT-COMMUNITYCONTACT-城乡社区联系方式");
        jedis.rpush("cxsqggaqspjk", "PT-COMMUNITYSPACE-城乡社区面积(平方米)");
        jedis.rpush("cxsqggaqspjk", "PT-COMMUNITYPERSONNUMBER-监控摄像机总数");
        jedis.rpush("cxsqggaqspjk", "PT-HDCAMERANUMBER-高清摄像机数量");
        jedis.rpush("cxsqggaqspjk", "PT-TOWNSHIPNETWORKCAMERANUMBER-联网摄像机数量");
        jedis.rpush("cxsqggaqspjk", "PT-DUTYFULLDAYCAMERANUMBER-值守摄像机数量");
        jedis.rpush("cxsqggaqspjk", "PT-PERSQUAREKMCAMERANUMBER-每平方公里摄像机数量");
        jedis.rpush("cxsqggaqspjk", "PT-PERHUNDREDPEOPLECAMERANUMBER-每百人摄像机数量");

        jedis.del("xx");
        jedis.rpush("xx", "PT-ORG_NAME-所属网格");
        jedis.rpush("xx", "PT-SCHOOLNAME-学校名称");
        jedis.rpush("xx", "PT-SCHOOLADDRESS-学校地址");
        jedis.rpush("xx", "DICT-SCHOOLTYPE|SCHOOLTYPEID-xxbxlx|学校办学类型");
        jedis.rpush("xx", "PT-ADMINISTRATIVEDEPARTMENT-学校主管教育行政部门");
        jedis.rpush("xx", "PT-STUDENTSINSCHOOLNUMBER-在校学生人数");
        jedis.rpush("xx", "PT-PRINCIPALNAME-校长姓名");
        jedis.rpush("xx", "PT-PRINCIPALCONTACT-校长联系方式");
        jedis.rpush("xx", "PT-PUTSECURITYINCHARGENAME-分管保卫责任人姓名");
        jedis.rpush("xx", "PT-PUTSECURITYINCHARGECONTACT-分管保卫责任人联系方式");
        jedis.rpush("xx", "PT-SECURITYINCHARGENAME-安全保卫责任人姓名");
        jedis.rpush("xx", "PT-SECURITYINCHARGECONTACT-安全保卫责任人联系方式");
        jedis.rpush("xx", "PT-POLICEINCHARGENAME-治安责任人姓名");
        jedis.rpush("xx", "PT-POLICEINCHARGECONTACT-治安责任人联系方式");
        jedis.rpush("xx", "PT-SECURITYNUMBER-安全保卫人数");

        jedis.del("jbxxtemp");
        jedis.rpush("jbxxtemp", "PT-CITIZENIDNO-公民身份证号");
        jedis.rpush("jbxxtemp", "PT-NAME-姓名");
        jedis.rpush("jbxxtemp", "PT-USEDNAME-曾用名");
        jedis.rpush("jbxxtemp", "PT-ORG_NAME-所属网格");
        jedis.rpush("jbxxtemp", "DICT-GENDER|GENDERID-xb|性别");
        jedis.rpush("jbxxtemp", "PT-BIRTHDATE-出生日期");
        jedis.rpush("jbxxtemp", "DICT-NATION|NATIONID-mz|民族");
        jedis.rpush("jbxxtemp", "PT-ORIGINPLACE-籍贯");
        jedis.rpush("jbxxtemp", "DICT-MARITALSTATUS|MARITALSTATUSID-hyzk|婚姻状况");
        jedis.rpush("jbxxtemp", "DICT-POLITICALSTATUS|POLITICALSTATUSID-zzmm|政治面貌");
        jedis.rpush("jbxxtemp", "DICT-EDUCATION|EDUCATIONID-xl|学历");
        jedis.rpush("jbxxtemp", "DICT-RELIGIONFAITH|RELIGIONFAITHID-zjxy|宗教信仰");
        jedis.rpush("jbxxtemp", "DICT-OCCUPATIONTYPE|OCCUPATIONTYPEID-zylb|职业类别");
        jedis.rpush("jbxxtemp", "PT-OCCUPATION-职业");
        jedis.rpush("jbxxtemp", "PT-SERVICEPLACE-服务处所");
        jedis.rpush("jbxxtemp", "PT-CONTACT-联系方式");
        jedis.rpush("jbxxtemp", "PT-DOMICILEPLACE-户籍地");
        jedis.rpush("jbxxtemp", "PT-DOMICILEPLACEDETAILS-户籍门(楼)详址");
        jedis.rpush("jbxxtemp", "PT-PRESENTPLACE-现住地");
        jedis.rpush("jbxxtemp", "PT-PRESENTPLACEDETAILS-现住门(楼)详址");

        jedis.close();
    }
}
